# Generated by Django 4.1.1 on 2022-09-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('power_level', models.CharField(max_length=32)),
                ('transformation', models.CharField(max_length=32)),
            ],
        ),
    ]
